//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ninjaT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espada()
        {
            this.espadasUsuario = new HashSet<espadasUsuario>();
        }
    
        public int id { get; set; }
        public string espada1 { get; set; }
        public Nullable<double> preco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<espadasUsuario> espadasUsuario { get; set; }
    }
}
